In [2]:
import pandas as pd
import os

In [ ]:
os.listdir("../Datasets_GPT_Output")

['.DS_Store',
 'Discrete_Emotions',
 'Offensiveness',
 'Moral Foundations',
 'Sentiment',
 'News_headlines']

## Discrete emotions

#### English

In [53]:
eng_3_5 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT3.5/emotion-class-english-3.5_temp=0.csv")
eng_4 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT4/emotion-tweets-3-gpt-4-0-1.csv")
eng_4t = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT4 Turbo/emotion-english-0-gpt-4-0125-preview-0-1 (4).csv")

In [54]:
eng_3_5.rename({"gpt": "GPT3.5"}, axis=1, inplace=True)

In [55]:
label_dict_eng = {"anger": 1, "joy": 2, "sadness":3, "optimism":4, "love":4}


eng_4['GPT4'] = pd.from_dummies(eng_4[["anger", "joy", "sadness", "optimism"]])
eng_4 = eng_4.replace({"GPT4": label_dict_eng})

In [56]:
eng_4t = eng_4t.rename({'gpt4':'gpt4t'}, axis = 1)
eng_4t

,Unnamed: 0,Tweet,anger,joy,sadness,optimism,gpt4t
0,1,#Deppression is real. Partners w/ #depressed p...,0,0,1,0,3.0
1,2,@POLITICOEurope Interesting choice of words......,1,0,0,0,1.0
2,3,My visit to hospital for care triggered #traum...,0,0,1,0,3.0
3,4,@MPSNutrition Welcome to #MPSVT! We are deligh...,0,1,0,0,2.0
4,5,What makes you feel #joyful?,0,1,0,0,2.0
...,...,...,...,...,...,...,...
1416,1417,I need a sparkling bodysuit . No occasion. Jus...,0,1,0,0,2.0
1417,1418,@everybodyzzmama I've finished reading it; sim...,0,0,1,0,3.0
1418,1419,shaft abrasions from panties merely shifted to...,1,0,0,0,1.0
1419,1420,All this fake outrage. Y'all need to stop 🤣,1,0,0,0,2.0
1420,1421,Would be ever so grateful if you could record ...,0,1,0,0,2.0

In [57]:
full_eng = eng_3_5.loc[:, ["Tweet", "human", "GPT3.5"]]
full_eng['GPT4'] = eng_4['GPT4']
full_eng['GPT4-Turbo'] = eng_4t['gpt4t'].astype(int)
full_eng.head(10)

,Tweet,human,GPT3.5,GPT4,GPT4-Turbo
0,#Deppression is real. Partners w/ #depressed p...,3,3,3,3
1,@POLITICOEurope Interesting choice of words......,1,1,1,1
2,My visit to hospital for care triggered #traum...,3,3,3,3
3,@MPSNutrition Welcome to #MPSVT! We are deligh...,2,2,2,2
4,What makes you feel #joyful?,2,2,2,2
5,i am revolting.,1,3,1,1
6,Rin might ever appeared gloomy but to be a mel...,3,3,3,3
7,In need of a change! #restless,3,4,4,4
8,@mattsamatt @jasonosia #cmbyn does screen Aug...,3,4,2,2
9,@FS1 Get Donovan out of your soccer booth. He'...,1,1,1,1

In [58]:
full_eng.to_csv("../clean_data/emotion_twitter_english.csv", index=False)

#### Indonesian

In [100]:
ind_3_5 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT3.5/emotion-class-Indonesian-GPT-temp=0.csv")
ind_4 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT4/emotion-indonesian-0-gpt-4-0-1.csv")

In [103]:
ind_3_5.rename({"gpt": "GPT3.5"}, axis=1, inplace=True)

ind_3_5.head()

,Unnamed: 0,label,tweet,human,GPT3.5
0,1,love,Pixy ini kok lama-lama gemesim yaaaa. Setelah ...,4,5
1,2,fear,Penyakit hepatitis B 100x lebih infeksius dari...,2,2
2,3,fear,[USERNAME] [USERNAME] [USERNAME] Gw lebih khaw...,2,2
3,4,anger,Kemerdekaan adalah hak segala bangsa ...( Kec ...,1,1
4,5,happy,"Selamat pak [USERNAME] resmi jadi bapak, seked...",5,5

In [102]:
label_dict_ind = {"anger": 1, "fear": 2, "sadness": 3, "love": 4, "joy": 5}


ind_4['GPT4'] = pd.from_dummies(ind_4[["anger", "fear", "sadness", "love", "joy"]])
ind_4 = ind_4.replace({"GPT4": label_dict_ind})

In [104]:
full_ind = ind_4.loc[: , ["Tweet"]]
full_ind['human'] = ind_3_5['human']
full_ind['GPT3.5'] = ind_3_5['GPT3.5']
full_ind['GPT4'] = ind_4['GPT4']

In [106]:
full_ind.to_csv("../clean_data/emotion_twitter_indonesian.csv", index=False)

# Moral foundations

In [21]:
gpt4_auth = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4/MFRC-authority (1)")
gpt4_care = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4/MFRC-care")
gpt4_eq = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4/MFRC-equality")
gpt4_loy = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4/MFRC-loyalty")
gpt4_morsent = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4/MFRC-moral_sentiment")
gpt4_prop = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4/MFRC-proportionality")
gpt4_pur = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4/MFRC-purity")

In [22]:
gpt4_auth

,Unnamed: 0.1,Unnamed: 0,text_id,bucket,text,Care,Equality,Proportionality,Loyalty,Authority,Purity,Thin Morality,Non-Moral,is_moral,question_authority
0,0,0,dbv1hkq_INCAS_equality,French politics,So Le Pen is just anti-EU for its own sake? Sh...,0,0,1,1,0,0,0,0,1,0
1,1,1,dbv1wa1_INCAS_proportionality,French politics,Qatar really isn't that huge in international ...,1,0,0,1,0,0,0,0,1,0
2,2,2,dbv46y0_INCAS_loyalty,French politics,"&gt; He also warned François Fillon, the candi...",0,0,0,0,0,0,0,1,0,0
3,3,3,dbv5fcm_INCAS_care,French politics,"Indeed, Mr Hollande. And you have played your ...",0,0,0,0,0,0,0,1,0,0
4,4,4,dbv5vga_INCAS_random,French politics,I agree RTs primary purpose is such but the pe...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16127,16127,17893,glix4yz_everyday_purity,Everyday Morality,NTA your sexuality is your business and gay or...,0,1,0,0,0,0,0,0,1,0
16128,16128,17894,glixzxg_everyday_purity,Everyday Morality,YES cramps can be more than just uncomfortable...,0,0,0,0,0,0,0,1,0,0
16129,16129,17895,glizfbj_everyday_proportionality,Everyday Morality,Those are all so fucking gross. I never liked...,0,0,0,0,0,0,0,1,0,0
16130,16130,17896,glizsjx_politics_random,US Politics,Would him going up there and spouting all that...,0,0,0,0,0,0,0,1,0,0
16131,16131,17897,glj3eq8_everyday_random,Everyday Morality,This sounds like it may be long term effects f...,0,0,0,0,0,0,0,1,0,0

In [14]:
moral_full = gpt4_auth.loc[:, "text":]

In [23]:
moral_full = moral_full.rename({"question_authority": "GPT4_Authority"}, axis=1)
moral_full['GPT4_Care'] = gpt4_care['questionCare']
moral_full['GPT4_Equality'] = gpt4_eq['question_equality']
moral_full['GPT4_Loyalty'] = gpt4_loy['question_loyalty']
moral_full['GPT4_MoralSentiment'] = gpt4_morsent['question_moral_sentiment']
moral_full['GPT4_Proportionality'] = gpt4_prop['question_proportionality']
moral_full['GPT4_Purity'] = gpt4_pur['question_purity']

In [25]:
gpt4t_auth = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4 Turbo/MFRC-authority-gpt-4-0125-preview")
gpt4t_eq = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4 Turbo/MFRC-equality-gpt-4-0125-preview")
gpt4t_loy = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4 Turbo/MFRC-loyalty-gpt-4-0125-preview")
gpt4t_morsent = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4 Turbo/MFRC-moral_sentiment-gpt-4-0125-preview")
gpt4t_prop = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4 Turbo/MFRC-proportionality-gpt-4-0125-preview")
gpt4t_pur = pd.read_csv("../Datasets_GPT_Output/Moral Foundations/GPT4 Turbo/MFRC-purity-gpt-4-0125-preview")

In [28]:
moral_full['GPT4-Turbo_Authority'] = gpt4t_auth['question_authority']
moral_full['GPT4-Turbo_Equality'] = gpt4t_eq['question_equality']
moral_full['GPT4-Turbo_Loyalty'] = gpt4t_loy['question_loyalty']
moral_full['GPT4-Turbo_MoralSentiment'] = gpt4t_morsent['question_moral_sentiment']
moral_full['GPT4-Turbo_Proportionality'] = gpt4t_prop['question_proportionality']
moral_full['GPT4-Turbo_Purity'] = gpt4t_pur['question_purity']

In [30]:
moral_full.to_csv("../clean_data/moral-foundations_reddit_english.csv", index=False)

# News headlines - sentiment and emotions, Likert scale

In [127]:
gpt3_5_news = pd.read_csv("../Datasets_GPT_Output/News_headlines/GPT3.5/NewsHeadlinesOutput.csv")

In [128]:
news_full = gpt3_5_news.rename({'headlines.headline': 'text',
                                  'gptsentiment': 'GPT3.5_Sentiment',
                                  'gptanger': 'GPT3.5_Anger',
                                  'gptjoy': 'GPT3.5_Joy',
                                  'gptsadness': 'GPT3.5_Sadness',
                                  'gptfear': 'GPT3.5_Fear'}, axis=1)

In [129]:
gpt4_news_anger = pd.read_csv("../Datasets_GPT_Output/News_headlines/GPT4/emotion-news-headlines-anger-0-gpt-4-0-1.csv")
gpt4_news_fear= pd.read_csv("../Datasets_GPT_Output/News_headlines/GPT4/emotion-news-headlines-fear-0-gpt-4-0-1 (1).csv")
gpt4_news_joy = pd.read_csv("../Datasets_GPT_Output/News_headlines/GPT4/emotion-news-headlines-joy-0-gpt-4-0-1 (1).csv")
gpt4_news_sadness = pd.read_csv("../Datasets_GPT_Output/News_headlines/GPT4/emotion-news-headlines-sadness-0-gpt-4-0-1.csv")
gpt4_news_sent = pd.read_csv("../Datasets_GPT_Output/News_headlines/GPT4/sentiment-news-headlines-0-gpt-4-0-1.csv")

In [130]:
news_full['GPT4_Sentiment'] = gpt4_news_sent['sentiment']
news_full['GPT4_Anger'] = gpt4_news_anger['anger']
news_full['GPT4_Joy'] = gpt4_news_joy['joy']
news_full['GPT4_Sadness'] = gpt4_news_sadness['sadness']
news_full['GPT4_Fear'] = gpt4_news_fear['fear']

In [131]:
gpt4t_news = pd.read_csv('../Datasets_GPT_Output/News_headlines/GPT4 Turbo/dataNHBTurboOutput.csv')

In [132]:
gpt4t_news = gpt4t_news.rename({'headlines.headline': 'text',
                                'gptsentimentTurbo': 'GPT4-Turbo_Sentiment',
                                  'gptangerTurbo': 'GPT4-Turbo_Anger',
                                  'gptjoyTurbo': 'GPT4-Turbo_Joy',
                                  'gptsadnessTurbo': 'GPT4-Turbo_Sadness',
                                  'gptfearTurbo': 'GPT4-Turbo_Fear'}, axis=1)

In [133]:
gpt4t_news = gpt4t_news.drop(['gptsentiment', 'ggptjoyTurbo'], axis=1)

In [134]:
gpt4t_news

,text,sentiment,anger,fear,joy,sadness,GPT4-Turbo_Sentiment,GPT4-Turbo_Anger,GPT4-Turbo_Joy,GPT4-Turbo_Sadness,GPT4-Turbo_Fear
0,"It's Dirty, It's Rich, And You Can Totally Mak...",4.500,1.750,1.375,3.500,1.375,6,1,5,1,1
1,His Fake Phone Call Is Exactly What Happens Wh...,3.400,2.625,1.625,1.250,2.250,4,2,2,2,2
2,If $23 Dollars An Hour Sounds Like A Lotta Dou...,5.500,1.375,1.375,3.625,1.250,4,1,5,1,1
3,McDonalds' CEO Would Love To Buy This Girl A H...,5.100,1.625,1.250,2.625,1.125,4,2,3,2,2
4,A political party in the U.K. just did the abs...,2.200,5.000,2.125,1.250,2.500,1,5,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...
208,"On International Women's Day, these three wome...",5.000,2.500,2.100,2.600,2.100,6,1,5,1,1
209,A Teen Came Out To His Mom. I Don't Think He S...,3.625,2.100,2.700,1.900,3.100,4,1,5,2,2
210,Here's Why Helping Others Feels So Much Better...,5.375,2.100,1.600,4.500,1.900,7,1,7,1,1
211,"They're about 1% the size of a human, but we n...",4.625,1.800,2.100,2.300,1.800,6,1,5,2,2
212,This Boys Parents Didn't Know He'd Commit A Cr...,2.875,3.200,4.100,1.300,4.800,3,2,1,4,3

In [135]:
news_full

,text,sentiment,anger,fear,joy,sadness,GPT3.5_Sentiment,GPT3.5_Anger,GPT3.5_Joy,GPT3.5_Sadness,GPT3.5_Fear,GPT4_Sentiment,GPT4_Anger,GPT4_Joy,GPT4_Sadness,GPT4_Fear
0,"It's Dirty, It's Rich, And You Can Totally Mak...",4.500,1.750,1.375,3.500,1.375,6,1,6,1,1,4.0,1.0,5.0,1.0,1.0
1,His Fake Phone Call Is Exactly What Happens Wh...,3.400,2.625,1.625,1.250,2.250,5,1,4,1,1,3.0,2.0,3.0,1.0,2.0
2,If $23 Dollars An Hour Sounds Like A Lotta Dou...,5.500,1.375,1.375,3.625,1.250,6,1,5,1,1,4.0,2.0,4.0,1.0,1.0
3,McDonalds' CEO Would Love To Buy This Girl A H...,5.100,1.625,1.250,2.625,1.125,6,1,6,1,1,5.0,2.0,5.0,3.0,1.0
4,A political party in the U.K. just did the abs...,2.200,5.000,2.125,1.250,2.500,2,6,3,2,5,1.0,5.0,2.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,"On International Women's Day, these three wome...",5.000,2.500,2.100,2.600,2.100,7,1,6,1,1,5.0,1.0,5.0,2.0,1.0
209,A Teen Came Out To His Mom. I Don't Think He S...,3.625,2.100,2.700,1.900,3.100,5,2,6,5,5,6.0,1.0,5.0,4.0,1.0
210,Here's Why Helping Others Feels So Much Better...,5.375,2.100,1.600,4.500,1.900,7,1,6,1,1,6.0,1.0,6.0,1.0,1.0
211,"They're about 1% the size of a human, but we n...",4.625,1.800,2.100,2.300,1.800,6,1,5,1,1,5.0,1.0,3.0,2.0,2.0
212,This Boys Parents Didn't Know He'd Commit A Cr...,2.875,3.200,4.100,1.300,4.800,2,2,2,4,4,2.0,3.0,2.0,5.0,4.0

In [136]:
news_full = pd.concat([news_full, gpt4t_news.loc[:, "GPT4-Turbo_Sentiment":]], axis=1)

In [138]:
news_full.to_csv("../clean_data/emotion-sentiment_news_english.csv", index=False)

# Offensiveness

In [279]:
off_3_eng = pd.read_csv("../Datasets_GPT_Output/Offensiveness/GPT3.5/EnglishOffensiveOutput.csv")
off_4_eng = pd.read_csv("../Datasets_GPT_Output/Offensiveness/GPT4/offensive-english-0-gpt-4-0-1.csv")
off_4t_eng = pd.read_csv("../Datasets_GPT_Output/Offensiveness/GPT4 Turbo/offensive-english-0-gpt-4-0125-preview-0-1.csv")

In [280]:
off_3_tur = pd.read_csv("../Datasets_GPT_Output/Offensiveness/GPT3.5/offenseval-Turkish-GPT.csv")
off_4_tur = pd.read_csv("../Datasets_GPT_Output/Offensiveness/GPT4/offensive-turkish-0-gpt-4-0-1.csv")
off_4t_tur = pd.read_csv("../Datasets_GPT_Output/Offensiveness/GPT4 Turbo/offensive-turkish-0-gpt-4-0125-preview-0-1.csv",sep=";")

In [281]:
def create_off_df(df1, df2, df3):
    full = df1.loc[: , "tweet":]
    full = full.rename({"gpt": "GPT3.5"},axis=1)

    full['GPT4'] = df2['offensive'].astype(int)
    full['GPT4-Turbo'] = df3['gpt4'].astype(int)

    return full

In [282]:
off_3_eng = off_3_eng.rename({'text':"tweet"}, axis=1)

full_off_eng = create_off_df(off_3_eng, off_4_eng, off_4t_eng)
full_off_tur = create_off_df(off_3_tur, off_4_tur, off_4t_tur)

In [283]:
full_off_eng.to_csv("../clean_data/offensive_twitter_english.csv", index=False)
full_off_tur.to_csv("../clean_data/offensive_twitter_turkish.csv", index=False)

# Sentiment - multilingual tweets

In [ ]:
sent_dict = {"positive": 1, "neutral": 2, "negative":3}

#### Amharic

In [238]:
# Amharic
amharic_3 = pd.read_csv("../Datasets_GPT_Output/Sentiment/GPT3.5/AmharicSentimentOutput.csv")
amharic_4 = pd.read_csv("../Datasets_GPT_Output/Sentiment/GPT4/sentiment-amharic-0-gpt-4-0-1.csv")
amharic_4t = pd.read_csv("../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-amharic-0-gpt-4-0125-preview-0-2.csv")

In [ ]:
amharic_full = amharic_3.rename({"gpt": "GPT3.5"}, axis=1)
amharic_full['GPT4'] = amharic_4['gpt4']
amharic_full['GPT4-Turbo'] = amharic_4t['gpt4']

In [ ]:
amharic_full = amharic_full.convert_dtypes(infer_objects=False, convert_string=False)

amharic_full.to_csv('../clean_data/sentiment_twitter_amharic.csv', index=False)

#### Arabic

In [272]:
arabic_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/sentiment-arabic-3.5-temp0.csv')
arabic_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-arabic-0-gpt-4-0-1.csv')
arabic_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-arabic-0-gpt-4-0125-preview-0-1.csv')

In [273]:
arabic_4['GPT4'] = pd.from_dummies(arabic_4[["positive", "neutral", "negative"]])
arabic_4 = arabic_4.replace({"GPT4": sent_dict})

In [274]:
arabic_full = arabic_3.rename({'gpt': 'GPT3.5', 'text': 'tweet'}, axis=1).loc[: , ['id','tweet', 'human', 'GPT3.5']]
arabic_full['GPT4'] = arabic_4['GPT4']
arabic_full['GPT4-Turbo'] = arabic_4t['gpt4']

In [278]:
arabic_full.to_csv('../clean_data/sentiment_twitter_arabic.csv', index=False)

In [277]:
arabic_full

,id,tweet,human,GPT3.5,GPT4,GPT4-Turbo
0,8.001000e+17,@Alito_NBA جواب ذكي 😂,1,1,1.0,1.0
1,8.001002e+17,@its_NBA @ssrg90 كلام سليم,2,2,1.0,1.0
2,8.001038e+17,@nba_155 ياخزياه بس صارخت صراخ وازعجتكم مشكلة ...,3,2,3.0,3.0
3,8.001055e+17,@nba_155 صوتي راح اقولك 💔,2,3,3.0,3.0
4,8.001059e+17,@Alito_NBA انا ماخفت من شي الا ان يكون عقلية م...,3,3,3.0,3.0
...,...,...,...,...,...,...
6095,8.108233e+17,تقول نوال الزغبي : https://t.co/BozQHk3pJU,2,2,NaN,NaN
6096,8.108281e+17,سيلفي للفنانة 👇الذهبية #نوال_الزغبي @NawalElZo...,1,1,NaN,NaN
6097,8.108328e+17,فنانة لبنانية كبيرة صوتها إسطوري ؟! #ماجدة_ال...,1,2,NaN,NaN
6098,8.108378e+17,"@i_7md تذكرني بأغنية نوال الزغبي عينيك كدابين""",1,2,NaN,NaN
6099,8.108634e+17,نوال الزغبي لطيفه الفنانه الوحيده اللي كل الفي...,1,1,NaN,NaN

#### English

In [294]:
sent_eng_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/SentimentEnglishOutput.csv')
sent_eng_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-english-0-gpt-4-0-1 (1).csv')
sent_eng_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-english-0-gpt-4-0125-preview-0-1.csv')

In [295]:
sent_eng_4['GPT4'] = pd.from_dummies(sent_eng_4[["positive", "neutral", "negative"]])
sent_eng_4 = sent_eng_4.replace({"GPT4": sent_dict})

In [296]:
sent_eng_full = sent_eng_3.rename({'gpt': 'GPT3.5', 'text':'tweet'},axis=1).loc[:, ['id', 'tweet', 'human', 'GPT3.5']]

sent_eng_full['GPT4'] = sent_eng_4['GPT4']
sent_eng_full['GPT4-Turbo'] = sent_eng_4t['gpt4']

In [298]:
sent_eng_full.to_csv('../clean_data/sentiment_twitter_english.csv', index=False)

#### Hausa

In [301]:
hausa_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/HausaSentimentOutput.csv')
hausa_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-hau-0-gpt-4-0-1.csv')
hausa_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-hausa-0-gpt-4-0125-preview-0-2.csv')

In [309]:
hausa_full = hausa_3.rename({'gpt': 'GPT3.5'}, axis=1)
hausa_full['GPT4'] = hausa_4['gpt4'].astype(int)
hausa_full['GPT4-Turbo'] = hausa_4t['gpt4'].astype(int)

In [312]:
hausa_full.to_csv('../clean_data/sentiment_twitter_hausa.csv',index=False)

#### Igbo

In [320]:
igbo_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/IboSentimentOutput.csv')
igbo_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-ibo-0-gpt-4-0-1.csv')
igbo_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-igbo-0-gpt-4-0125-preview-0-2.csv')

In [321]:
igbo_full = igbo_3.rename({'gpt': 'GPT3.5'}, axis=1)
igbo_full['GPT4'] = igbo_4['gpt4'].astype(int)
igbo_full['GPT4-Turbo'] = igbo_4t['gpt4'].astype(int)

In [323]:
igbo_full.to_csv('../clean_data/sentiment_twitter_igbo.csv',index=False)

#### Kinyarwanda

In [324]:
kiny_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/sentiment-kinyarwanda-3.5.csv')
kiny_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-kinyarwanda-0-gpt-4-0-1.csv')
kiny_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-kinyarwanda-0-gpt-4-0125-preview-0-2.csv')

In [330]:
kiny_full = kiny_3.rename({'gpt': 'GPT3.5', 'text':'tweet'}, axis=1).loc[:, 'tweet':]
kiny_full['GPT4'] = kiny_4['gpt4'].astype(int)
kiny_full['GPT4-Turbo'] = kiny_4t['gpt4'].astype(int)

In [332]:
kiny_full.to_csv('../clean_data/sentiment_twitter_kinyarwanda.csv',index=False)

#### Swahili

In [333]:
swa_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/sentiment-swahili-3.5.csv')
swa_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-swahili-0-gpt-4-0-1.csv')
swa_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-swahili-0-gpt-4-0-1.csv')

In [338]:
swa_full = swa_3.rename({'gpt': 'GPT3.5', 'text':'tweet'}, axis=1).loc[:, 'tweet':]
swa_full['GPT4'] = swa_4['gpt4'].astype(int)
swa_full['GPT4-Turbo'] = swa_4t['gpt4'].astype(int)

In [340]:
swa_full.to_csv('../clean_data/sentiment_twitter_swahili.csv',index=False)

#### Tsonga

In [341]:
tso_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/TsongaSentimentOutput.csv')
tso_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-tsonga-0-gpt-4-0-1.csv')
tso_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-tsonga-0-gpt-4-0125-preview-0-2.csv')

In [346]:
tso_full = tso_3.rename({'GPT': 'GPT3.5', 'text':'tweet'}, axis=1).loc[:, 'tweet':'GPT3.5']
tso_full['GPT4'] = tso_4['gpt4'].astype(int)
tso_full['GPT4-Turbo'] = tso_4t['gpt4'].astype(int)

In [348]:
tso_full.to_csv('../clean_data/sentiment_twitter_tsonga.csv',index=False)

#### Twi

In [350]:
twi_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/sentiment-twi-3.5.csv')
twi_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-twi-0-gpt-4-0-1.csv')
twi_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-twi-0-gpt-4-0125-preview-0-2.csv')

In [355]:
twi_full = twi_3.rename({'gpt': 'GPT3.5', 'text':'tweet'}, axis=1).loc[:, 'id':]
twi_full['GPT4'] = twi_4['gpt4'].astype(int)
twi_full['GPT4-Turbo'] = twi_4t['gpt4'].astype(int)

In [357]:
twi_full.to_csv('../clean_data/sentiment_twitter_twi.csv',index=False)

#### Yoruba

In [358]:
yor_3 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT3.5/sentiment-yoruba-n=1000-3.5.csv')
yor_4 = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT4/sentiment-yoruba-0-gpt-4-0-1.csv')
yor_4t = pd.read_csv('../Datasets_GPT_Output/Sentiment/GPT 4 Turbo/sentiment-yoruba-0-gpt-4-0125-preview-0-2.csv')

In [359]:
yor_full = yor_3.rename({'gpt': 'GPT3.5', 'text':'tweet'}, axis=1).loc[:, 'id':]
yor_full['GPT4'] = yor_4['gpt4'].astype(int)
yor_full['GPT4-Turbo'] = yor_4t['gpt4'].astype(int)

,Unnamed: 0,id,text,human,gpt
0,1,yo_test_00693,ìyáa wa láti iléifẹ́ ní kí àwa ọkùnrin ó gba o...,1,2
1,2,yo_test_02283,tanfírí ni à ń pe ìpanu yìí ẹ̀pà ni a fi ń ṣe ...,2,2
2,3,yo_test_03354,láyé àtijọ́ àwọn àwòràwọ̀ í ma á na ọ̀pá àṣẹ s...,2,2
3,4,yo_test_02280,kíni ìtumọ̀ irínwó ní orúkọ ìṣirò owó ẹyọ ló j...,2,2
4,5,yo_test_03778,óóga o alákòwé à fi sùúrù o nkan ńbẹ ẹ̀yin èèy...,3,2
...,...,...,...,...,...
995,996,yo_test_03254,tí ẹyẹ ò bá fín ẹyẹ níràn ojú ọrun tó ẹyẹ ẹ́ f...,2,2
996,997,yo_test_02924,láyée gbọ́nran à n fi irun orí dá àwọn èèyàn o...,2,2
997,998,yo_test_03861,o kò mọ́ wípé ó ní ohun tó bá dé nítorí òwòèmi...,3,3
998,999,yo_test_04288,gej gba gbere fun boko haramu ni nijeria amo r...,3,3
999,1000,yo_test_03465,ataoja ti osogboooni ti ileifeagbowu ti ilu og...,2,2

In [360]:
yor_4

,Unnamed: 0.1,Unnamed: 0,id,tweet,human,gpt,gpt4
0,0,1,yo_test_00693,ìyáa wa láti iléifẹ́ ní kí àwa ọkùnrin ó gba o...,1,2,2.0
1,1,2,yo_test_02283,tanfírí ni à ń pe ìpanu yìí ẹ̀pà ni a fi ń ṣe ...,2,2,2.0
2,2,3,yo_test_03354,láyé àtijọ́ àwọn àwòràwọ̀ í ma á na ọ̀pá àṣẹ s...,2,2,2.0
3,3,4,yo_test_02280,kíni ìtumọ̀ irínwó ní orúkọ ìṣirò owó ẹyọ ló j...,2,2,2.0
4,4,5,yo_test_03778,óóga o alákòwé à fi sùúrù o nkan ńbẹ ẹ̀yin èèy...,3,2,3.0
...,...,...,...,...,...,...,...
995,995,996,yo_test_03254,tí ẹyẹ ò bá fín ẹyẹ níràn ojú ọrun tó ẹyẹ ẹ́ f...,2,2,2.0
996,996,997,yo_test_02924,láyée gbọ́nran à n fi irun orí dá àwọn èèyàn o...,2,2,2.0
997,997,998,yo_test_03861,o kò mọ́ wípé ó ní ohun tó bá dé nítorí òwòèmi...,3,3,3.0
998,998,999,yo_test_04288,gej gba gbere fun boko haramu ni nijeria amo r...,3,3,3.0
999,999,1000,yo_test_03465,ataoja ti osogboooni ti ileifeagbowu ti ilu og...,2,2,2.0

In [361]:
yor_4t

,Unnamed: 0.1,Unnamed: 0,id,tweet,human,gpt,gpt4
0,0,1,yo_test_00693,ìyáa wa láti iléifẹ́ ní kí àwa ọkùnrin ó gba o...,1,2,2.0
1,1,2,yo_test_02283,tanfírí ni à ń pe ìpanu yìí ẹ̀pà ni a fi ń ṣe ...,2,2,1.0
2,2,3,yo_test_03354,láyé àtijọ́ àwọn àwòràwọ̀ í ma á na ọ̀pá àṣẹ s...,2,2,1.0
3,3,4,yo_test_02280,kíni ìtumọ̀ irínwó ní orúkọ ìṣirò owó ẹyọ ló j...,2,2,2.0
4,4,5,yo_test_03778,óóga o alákòwé à fi sùúrù o nkan ńbẹ ẹ̀yin èèy...,3,2,3.0
...,...,...,...,...,...,...,...
995,995,996,yo_test_03254,tí ẹyẹ ò bá fín ẹyẹ níràn ojú ọrun tó ẹyẹ ẹ́ f...,2,2,1.0
996,996,997,yo_test_02924,láyée gbọ́nran à n fi irun orí dá àwọn èèyàn o...,2,2,2.0
997,997,998,yo_test_03861,o kò mọ́ wípé ó ní ohun tó bá dé nítorí òwòèmi...,3,3,3.0
998,998,999,yo_test_04288,gej gba gbere fun boko haramu ni nijeria amo r...,3,3,3.0
999,999,1000,yo_test_03465,ataoja ti osogboooni ti ileifeagbowu ti ilu og...,2,2,2.0

In [ ]:
 = pd.read_csv('../')
.to_csv('../clean_data/')