In [2]:
import pandas as pd
import os

In [ ]:
os.listdir("../Datasets_GPT_Output")

['.DS_Store',
 'Discrete_Emotions',
 'Offensiveness',
 'Moral Foundations',
 'Sentiment',
 'News_headlines']

## Discrete emotions

#### English

In [94]:
eng_3_5 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT3.5/emotion-class-english-3.5_temp=0.csv")
eng_4 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT4/emotion-tweets-3-gpt-4-0-1.csv")
eng_4t = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT4 Turbo/emotion-english-0-gpt-4-0125-preview-0-1 (4).csv")

In [95]:
eng_3_5.rename({"gpt": "GPT3.5"}, axis=1, inplace=True)

In [96]:
label_dict_eng = {"anger": 1, "joy": 2, "sadness":3, "optimism":4, "love":4}


eng_4['GPT4'] = pd.from_dummies(eng_4[["anger", "joy", "sadness", "optimism"]])
eng_4 = eng_4.replace({"GPT4": label_dict_eng})

In [97]:
eng_4t = eng_4t.rename({'gpt4':'gpt4t'}, axis = 1)
eng_4t

,Unnamed: 0,Tweet,anger,joy,sadness,optimism,gpt4t
0,1,#Deppression is real. Partners w/ #depressed p...,0,0,1,0,3.0
1,2,@POLITICOEurope Interesting choice of words......,1,0,0,0,1.0
2,3,My visit to hospital for care triggered #traum...,0,0,1,0,3.0
3,4,@MPSNutrition Welcome to #MPSVT! We are deligh...,0,1,0,0,2.0
4,5,What makes you feel #joyful?,0,1,0,0,2.0
...,...,...,...,...,...,...,...
1416,1417,I need a sparkling bodysuit . No occasion. Jus...,0,1,0,0,2.0
1417,1418,@everybodyzzmama I've finished reading it; sim...,0,0,1,0,3.0
1418,1419,shaft abrasions from panties merely shifted to...,1,0,0,0,1.0
1419,1420,All this fake outrage. Y'all need to stop ðŸ¤£,1,0,0,0,2.0
1420,1421,Would be ever so grateful if you could record ...,0,1,0,0,2.0

In [98]:
full_eng = eng_3_5.loc[:, ["Tweet", "human", "GPT3.5"]]
full_eng['GPT4'] = eng_4['GPT4']
full_eng['GPT4_Turbo'] = eng_4t['gpt4t'].astype(int)
full_eng.head(10)

,Tweet,human,GPT3.5,GPT4,GPT4_Turbo
0,#Deppression is real. Partners w/ #depressed p...,3,3,3,3
1,@POLITICOEurope Interesting choice of words......,1,1,1,1
2,My visit to hospital for care triggered #traum...,3,3,3,3
3,@MPSNutrition Welcome to #MPSVT! We are deligh...,2,2,2,2
4,What makes you feel #joyful?,2,2,2,2
5,i am revolting.,1,3,1,1
6,Rin might ever appeared gloomy but to be a mel...,3,3,3,3
7,In need of a change! #restless,3,4,4,4
8,@mattsamatt @jasonosia #cmbyn does screen Aug...,3,4,2,2
9,@FS1 Get Donovan out of your soccer booth. He'...,1,1,1,1

In [99]:
full_eng.to_csv("../clean_data/emotion_twitter_english.csv", index=False)

#### Indonesian

In [100]:
ind_3_5 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT3.5/emotion-class-Indonesian-GPT-temp=0.csv")
ind_4 = pd.read_csv("../Datasets_GPT_Output/Discrete_Emotions/GPT4/emotion-indonesian-0-gpt-4-0-1.csv")

In [103]:
ind_3_5.rename({"gpt": "GPT3.5"}, axis=1, inplace=True)

ind_3_5.head()

,Unnamed: 0,label,tweet,human,GPT3.5
0,1,love,Pixy ini kok lama-lama gemesim yaaaa. Setelah ...,4,5
1,2,fear,Penyakit hepatitis B 100x lebih infeksius dari...,2,2
2,3,fear,[USERNAME] [USERNAME] [USERNAME] Gw lebih khaw...,2,2
3,4,anger,Kemerdekaan adalah hak segala bangsa ...( Kec ...,1,1
4,5,happy,"Selamat pak [USERNAME] resmi jadi bapak, seked...",5,5

In [102]:
label_dict_ind = {"anger": 1, "fear": 2, "sadness": 3, "love": 4, "joy": 5}


ind_4['GPT4'] = pd.from_dummies(ind_4[["anger", "fear", "sadness", "love", "joy"]])
ind_4 = ind_4.replace({"GPT4": label_dict_ind})

In [104]:
full_ind = ind_4.loc[: , ["Tweet"]]
full_ind['human'] = ind_3_5['human']
full_ind['GPT3.5'] = ind_3_5['GPT3.5']
full_ind['GPT4'] = ind_4['GPT4']

In [106]:
full_ind.to_csv("../clean_data/emotion_twitter_indonesian.csv", index=False)