In [1]:
import pandas as pd
# !pip install xlml

Defaulting to user installation because normal site-packages is not writeable
Collecting xlml
  Downloading XLML-0.1.2.tar.gz (2.3 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: xlml
  Building wheel for xlml (setup.py) ... done
  Created wheel for xlml: filename=XLML-0.1.2-py3-none-any.whl size=2541 sha256=276fa080371be7b64bfaefd18ecd08fce87b532e766567255203d79513069718
  Stored in directory: /Users/au643202/Library/Caches/pip/wheels/b1/87/2b/f97d88b215b86ef554032999f96decab1bd9ad04dbdc41fcad
Successfully built xlml
Installing collected packages: xlml
Successfully installed xlml-0.1.2

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [13]:
og = pd.read_excel('../dataverse_repo/data/original_sample/annotation_data_tweetscongress_raw.xlsx')

In [14]:
og

,status_id,user_id,screen_name,created_at,text,relevant,frame,notes
0,1466459124821020672,161411080,gracenapolitano,2021-12-02T17:27:55.000Z,The #BuildBackBetter Act is a once-in-a-genera...,NaN,NaN,NaN
1,1236328254731980802,815733290955112448,RepJayapal,2020-03-07T16:30:00.000Z,Everyone can take simple measures to protect t...,NaN,NaN,NaN
2,834076319650607104,240812994,RepYvetteClarke,2017-02-21T16:24:25.000Z,I will not participate in the normalization of...,NaN,NaN,NaN
3,976875688564322304,1134292500,RepBetoORourke,2018-03-22T17:38:08.000Z,At a time when twenty veterans a day are takin...,NaN,NaN,NaN
4,1383208627243220992,1081240074946252801,RepKirkpatrick,2021-04-17T00:00:10.000Z,It’s the federal government’s duty to deliver ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9997,1174789031844098048,1072008757,RepChrisStewart,2019-09-19T20:55:06.000Z,Today's CR vote was an easy NO. https://t.co/f...,NaN,NaN,NaN
9998,1061696058479140865,72198806,SenGillibrand,2018-11-11T19:04:00.000Z,The work that journalists do to be a watchdog ...,NaN,NaN,NaN
9999,835536185208401920,1061385474,RepLujanGrisham,2017-02-25T17:05:24.000Z,Getting ready to start our town hall. Watch li...,NaN,NaN,NaN
10000,1037714986322280448,2933760046,RepComstock,2018-09-06T14:51:47.000Z,Reuters: The number of Americans filing new cl...,NaN,NaN,NaN
10001,950853786674892800,1061385474,RepLujanGrisham,2018-01-09T22:16:23.000Z,Alex Azar is unfit to serve as Health and Huma...,NaN,NaN,NaN

### chatGPT_data

In [36]:
gpt_frames2_final = pd.read_csv('../dataverse_repo/data/chatGPT_data/training_data_frames_final.csv')
gpt_frames2_final

,Unnamed: 0,status_id,user_id,screen_name,created_at,text,relevant,frame,notes
0,0,861326915151384576,262756641,senorrinhatch,2017-05-07T21:08:33.000Z,"""I don't want my state picked on. I don't want...",1,fairness and equality,NaN
1,1,948309678429229056,462143773,RepCicilline,2018-01-02T21:47:00.000Z,Working people deserve #ABetterDeal than the o...,1,quality of life,NaN
2,2,1046837282169397248,28602948,RepRaulGrijalva,2018-10-01T19:00:32.000Z,The Trump Administration has replaced one cris...,1,policy prescription and evaluation,NaN
3,3,929353405075787776,242836537,SenatorLeahy,2017-11-11T14:21:32.000Z,So proud of #VT National Guard units and the V...,1,security and defense,NaN
4,4,989657325131763712,249787913,SenatorCarper,2018-04-27T00:07:47.000Z,"Tragically, unaccompanied children in @HHSGov’...",1,health and safety,NaN
...,...,...,...,...,...,...,...,...,...
1400,1992,975786634938667010,1061385474,RepLujanGrisham,2018-03-19T17:30:37.000Z,We need a national strategy to fix these issue...,1,policy prescription and evaluation,NaN
1401,1993,925112352890146816,1155335864,RepDonaldPayne,2017-10-30T21:29:07.000Z,"Despite the barrage of #ManafortMonday news, w...",1,other,NaN
1402,1994,1050809000596566017,2968007206,RepDeSaulnier,2018-10-12T18:02:43.000Z,During National Disability Employment Awarenes...,1,other,NaN
1403,1995,908719617929039872,216881337,RandPaul,2017-09-15T15:50:14.000Z,Discussing healthcare in Danville w/ local lea...,1,health and safety,NaN
1404,1996,898938610082361348,193794406,SenCapito,2017-08-19T16:04:00.000Z,Investing in our airports is important to our ...,1,economic,health

In [38]:
gpt_frames1_final = pd.read_csv('../dataverse_repo/data/chatGPT_data/training_data_problem_solution_final.csv')
gpt_frames1_final

,status_id,Date,text,relevant,relevant_check,problem_frame,problem_check,solution_frame,solution_check
0,1274037131636285443,2020-06-19T00:00:00Z,"The First Amendment binds the government, not ...",True,True,False,True,False,True
1,1236472965983657986,2020-03-08T00:00:00Z,"hi, my main acc @DEMINATIONIST is currently su...",True,True,False,True,False,True
2,1248195673771528194,2020-04-09T00:00:00Z,After a report showed a surge in misinformatio...,True,True,False,True,True,True
3,1313663759727067136,2020-10-07T00:00:00Z,Game 2 of the NLDS gets underway tomorrow at 2...,False,True,False,True,False,True
4,1224351561134022656,2020-02-03T00:00:00Z,"@connybush Sorry hun, Ive removed the tags on ...",False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...
2378,1233783871340208135,2020-02-29T00:00:00Z,@adopt_account I block when people unfollow...,False,True,False,True,False,True
2379,1259265991449739264,2020-05-09T00:00:00Z,#Facebook has banned the iconic photograph of ...,True,True,True,True,True,True
2380,1319959818111692800,2020-10-24T00:00:00Z,"Trump said he wouldn’t cut Medicaid, Social Se...",False,True,False,True,False,True
2381,1299334898789036032,2020-08-28T00:00:00Z,Falken duffel bag weekly #giveaway #contest. R...,False,True,False,True,False,True
2382,1317881149558083585,2020-10-18T00:00:00Z,Eleribu ni e ooo!\r\nStop using my name to spr...,True,True,False,True,True,True

In [39]:
gpt_stance_final = pd.read_excel('../dataverse_repo/data/chatGPT_data/training_data_stance_final.xlsx')
gpt_stance_final

,user_id,status_id,created_at,text,paula_stance_pro,fabio_stance_pro,paula_stance_neutral,fabio_stance_neutral,paula_stance_contra,fabio_stance_contra,stance pro,stance neutral,satance negative
0,274347607,1303485178946486272,2020-09-09T00:07:38.000Z,Isn’t it fascinating that my Twitter followers...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,851185827472441347,1334231659118555136,2020-12-02T20:23:11.000Z,@LG46776457 You don’t understand what Section ...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2510918743,1333116966811422722,2020-11-29T18:33:47.000Z,More people on Twitter should read this. And e...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,895019115483496448,1332475703359664128,2020-11-28T00:05:38.000Z,"“For purposes of National Security, Section 23...",0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,1312274637305384963,1347787201543888896,2021-01-09T06:08:04.000Z,A lot of big section 230 talk over the last ye...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1314288357577568257,1348772499539038209,2021-01-11T23:23:17.000Z,It's reputational shield to cover up a truly w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1496,15853002,1366663793485484037,2021-03-02T08:16:54.000Z,Utah Prematurely Tries To Dance On Section 230...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1497,1278381162365423617,1344450717147394048,2020-12-31T01:10:04.000Z,@softlinkie Section 230 repeal coming fast,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1498,214602946,1370315052222353409,2021-03-12T10:05:42.000Z,Breaking: Twitter Has Tried to Dismiss Lawsuit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1499,1359259253727494144,1377125183966732290,2021-03-31T05:06:44.000Z,@DanScavino Youtube just banned Steven crowder...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
gpt_topics_final = pd.read_csv('../dataverse_repo/data/chatGPT_data/training_data_topics_final.csv')
gpt_topics_final # same as RA frames 2 final

,status_id,Date,text,relevant,problem_frame,solution_frame,topic_check,frame_check,frame,topic
0,1348355481572499456,2021-01-10T00:00:00Z,"""Livestreamers"" with less than 100 concurrent ...",False,False,False,True,True,NaN,NaN
1,1348952923284369408,2021-01-12T00:00:00Z,Celebrities React to Donald Trump's Twitter Ba...,True,False,False,True,False,NaN,trump ban
2,1293654797967454208,2020-08-12T00:00:00Z,Trillion-dollar Big Tech monopolies claim they...,True,True,False,True,True,"law and order, crime and justice frames",section 230
3,1346989912432603136,2021-01-07T00:00:00Z,Fellow free-speech absolutists: How are you fe...,True,True,False,True,True,constitutionality and jurisprudency,trump ban
4,1235667474995179520,2020-03-05T00:00:00Z,"And yet won't ban Trump's account, I'm sure. h...",True,False,True,True,True,morality,platform policies
...,...,...,...,...,...,...,...,...,...,...
951,1367942544781438976,2021-03-05T00:00:00Z,VIDEO: Republican Governor Announces Bill Proh...,True,True,False,False,True,NaN,NaN
952,1375626755915067392,2021-03-27T00:00:00Z,Yep instagram is def shadow banning my post. F...,True,True,False,True,False,NaN,personal complaint
953,1352646471980437504,2021-01-22T00:00:00Z,@MollyJongFast @_ReaalAmerican_ Imagine follow...,True,False,False,True,True,political,general complaint
954,1349117542896459776,2021-01-12T00:00:00Z,maybe need to include new case book chapter on...,True,False,False,False,True,NaN,NaN
955,1344299056839979008,2020-12-30T00:00:00Z,Just figured something out. Trump wants Sectio...,True,False,False,True,True,economic,section 230

### RA  data

#### frames 2 task

In [49]:
ra_frames = pd.read_csv('../dataverse_repo/data/research_assistants_data/frames_task/training_data_frames.csv')
ra_frames

,status_id,user_id,screen_name,created_at,text,relevant,frame,notes
0,861326915151384576,262756641,senorrinhatch,2017-05-07T21:08:33Z,"""I don't want my state picked on. I don't want...",1,fairness and equality,NaN
1,948309678429229056,462143773,RepCicilline,2018-01-02T21:47:00Z,Working people deserve #ABetterDeal than the o...,1,quality of life,NaN
2,1046837282169397248,28602948,RepRaulGrijalva,2018-10-01T19:00:32Z,The Trump Administration has replaced one cris...,1,policy prescription and evaluation,NaN
3,929353405075787776,242836537,SenatorLeahy,2017-11-11T14:21:32Z,So proud of #VT National Guard units and the V...,1,security and defense,NaN
4,989657325131763712,249787913,SenatorCarper,2018-04-27T00:07:47Z,"Tragically, unaccompanied children in @HHSGov’...",1,health and safety,NaN
...,...,...,...,...,...,...,...,...
1400,975786634938667010,1061385474,RepLujanGrisham,2018-03-19T17:30:37Z,We need a national strategy to fix these issue...,1,policy prescription and evaluation,NaN
1401,925112352890146816,1155335864,RepDonaldPayne,2017-10-30T21:29:07Z,"Despite the barrage of #ManafortMonday news, w...",1,other,NaN
1402,1050809000596566017,2968007206,RepDeSaulnier,2018-10-12T18:02:43Z,During National Disability Employment Awarenes...,1,other,NaN
1403,908719617929039872,216881337,RandPaul,2017-09-15T15:50:14Z,Discussing healthcare in Danville w/ local lea...,1,health and safety,NaN
1404,898938610082361348,193794406,SenCapito,2017-08-19T16:04:00Z,Investing in our airports is important to our ...,1,economic,health

In [50]:
ra_politweets_frames = pd.read_csv('../dataverse_repo/data/research_assistants_data/frames_task/training_data_tweetscongress_frames.csv')
ra_politweets_frames

,status_id,user_id,screen_name,created_at,text,relevant_paula,relevant_fabio,frame_paula,frame_fabio,relvant_agreement_check,relevant,frames_agreement_check,frames_ra
0,861326915151384576,262756641,senorrinhatch,2017-05-07T21:08:33.000Z,"""I don't want my state picked on. I don't want...",1,1,morality,fairness and equality,True,1,False,NaN
1,948309678429229056,462143773,RepCicilline,2018-01-02T21:47:00.000Z,Working people deserve #ABetterDeal than the o...,1,1,quality of life,quality of life,True,1,True,quality of life
2,1046837282169397248,28602948,RepRaulGrijalva,2018-10-01T19:00:32.000Z,The Trump Administration has replaced one cris...,1,1,policy prescription and evaluation,policy prescription and evaluation,True,1,True,policy prescription and evaluation
3,929353405075787776,242836537,SenatorLeahy,2017-11-11T14:21:32.000Z,So proud of #VT National Guard units and the V...,1,1,security and defense,security and defense,True,1,True,security and defense
4,989657325131763712,249787913,SenatorCarper,2018-04-27T00:07:47.000Z,"Tragically, unaccompanied children in @HHSGov’...",1,1,health and safety,health and safety,True,1,True,health and safety
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,925112352890146816,1155335864,RepDonaldPayne,2017-10-30T21:29:07.000Z,"Despite the barrage of #ManafortMonday news, w...",1,1,health and safety,other,True,1,False,NaN
1762,1050809000596566017,2968007206,RepDeSaulnier,2018-10-12T18:02:43.000Z,During National Disability Employment Awarenes...,1,1,security and defense,other,True,1,False,NaN
1763,908719617929039872,216881337,RandPaul,2017-09-15T15:50:14.000Z,Discussing healthcare in Danville w/ local lea...,1,1,health and safety,health and safety,True,1,True,health and safety
1764,898938610082361348,193794406,SenCapito,2017-08-19T16:04:00.000Z,Investing in our airports is important to our ...,1,1,economic,economic,True,1,True,economic
1765,1057020849671299074,72198806,SenGillibrand,2018-10-29T21:26:23.000Z,I was delighted to tour and meet the students ...,1,1,other,NaN,True,1,False,NaN

In [54]:
ra_final_frames2 = pd.read_excel('../dataverse_repo/data/research_assistants_data/frames_task/tweets_annotation_data_ra_completed.xlsx')
ra_final_frames2

,status_id,Date,text,relevant,problem_frame,solution_frame,topic_name_fabio,topic_name_second_fabio,frame_name_primary_fabio,frame_name_secondary_fabio,topic_name_paula,topic_name_secondary_paula,frame_name_primary_paula,frame_name_secondary_paula
0,1348355481572499456,2021-01-10T00:00:00Z,"""Livestreamers"" with less than 100 concurrent ...",False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1348952923284369408,2021-01-12T00:00:00Z,Celebrities React to Donald Trump's Twitter Ba...,True,False,False,trump ban,NaN,other,NaN,trump ban,NaN,NaN,NaN
2,1293654797967454208,2020-08-12T00:00:00Z,Trillion-dollar Big Tech monopolies claim they...,True,True,False,section 230,general complaint,"law and order, crime and justice frames",constitutionality and jurisprudency,section 230,general complaint,"law and order, crime and justice frames",political
3,1346989912432603136,2021-01-07T00:00:00Z,Fellow free-speech absolutists: How are you fe...,True,True,False,trump ban,NaN,constitutionality and jurisprudency,NaN,trump ban,NaN,constitutionality and jurisprudency,NaN
4,1235667474995179520,2020-03-05T00:00:00Z,"And yet won't ban Trump's account, I'm sure. h...",True,False,True,platform policies,trump ban,morality,fairness and equality,platform policies,trump ban,morality,fairness and equality
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,1367942544781438976,2021-03-05T00:00:00Z,VIDEO: Republican Governor Announces Bill Proh...,True,True,False,platform policies,NaN,NaN,NaN,other,NaN,NaN,NaN
952,1375626755915067392,2021-03-27T00:00:00Z,Yep instagram is def shadow banning my post. F...,True,True,False,personal complaint,NaN,other,NaN,personal complaint,NaN,fairness and equality,policy prescription and evaluation
953,1352646471980437504,2021-01-22T00:00:00Z,@MollyJongFast @_ReaalAmerican_ Imagine follow...,True,False,False,general complaint,NaN,political,NaN,general complaint,NaN,political,security and defense frames
954,1349117542896459776,2021-01-12T00:00:00Z,maybe need to include new case book chapter on...,True,False,False,general complaint,NaN,NaN,NaN,other,NaN,NaN,NaN
955,1344299056839979008,2020-12-30T00:00:00Z,Just figured something out. Trump wants Sectio...,True,False,False,section 230,NaN,economic,NaN,section 230,NaN,economic,"law and order, crime and justice frames"

#### frames 1

In [57]:
ra_final_frames1 = pd.read_excel('../dataverse_repo/data/research_assistants_data/problem_solution_task/annotation_data_ra_completed.xlsx')
ra_final_frames1

,status_id,Date,text,relevant_paula,relevant_fabio,problem_frame_paula,problem_frame_fabio,solution_frame_paula,solution_frame_fabio
0,1274037131636285443,2020-06-19,"The First Amendment binds the government, not ...",1.0,1.0,0.0,0.0,0.0,0.0
1,1312433590693756928,2020-10-03,Check out our fringe at #Lab2020 with @antisem...,1.0,0.0,0.0,0.0,0.0,0.0
2,1236472965983657986,2020-03-08,"hi, my main acc @DEMINATIONIST is currently su...",1.0,1.0,0.0,0.0,0.0,0.0
3,1248195673771528194,2020-04-09,After a report showed a surge in misinformatio...,1.0,1.0,0.0,0.0,1.0,1.0
4,1313663759727067136,2020-10-07,Game 2 of the NLDS gets underway tomorrow at 2...,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4995,1268582213970362368,2020-06-04,This man started an account where he tweets ex...,NaN,NaN,NaN,NaN,NaN,NaN
4996,1320592590979371010,2020-10-26,Pakistani PM Khan calls on Facebook to ban all...,NaN,NaN,NaN,NaN,NaN,NaN
4997,1312037128449138688,2020-10-02,@SupportRequests #0174895295 the google accoun...,NaN,NaN,NaN,NaN,NaN,NaN
4998,1256665133587279872,2020-05-02,@Yakekoge @NancyHazen16 @lisalbarjas1 @dieteri...,NaN,NaN,NaN,NaN,NaN,NaN
4999,1287068465908588550,2020-07-25,If anyone has managed to download and save any...,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
ra_final_frames1_newtweets = pd.read_excel('../dataverse_repo/data/research_assistants_data/problem_solution_task/annotation_data_tweets23_ra_completed.xlsx')
ra_final_frames1_newtweets

,user_id,screen_name,status_id,created_at,text,relevant_fabio,relevant_paula,problem_frame_fabio,problem_frame_paula,solution_frame_fabio,solution_frame_paula
0,1586464459341504512,Pis0Mojado,1609636314621825024,2023-01-01T19:42:57.000Z,@BluesElmwood @2457klhu @jkoff609 @EducatingTr...,0.0,0.0,NaN,NaN,NaN,NaN
1,1529601130585538560,sodascentpack,1613316249085157378,2023-01-11T23:25:42.000Z,@skribblipoo_ im pretty sure they got suspende...,1.0,1.0,0.0,0.0,0.0,0.0
2,820753878845165568,lawyerchronicle,1618917829981634561,2023-01-27T10:24:23.000Z,@amerxmirza I have reported him to make sure h...,1.0,1.0,0.0,0.0,1.0,1.0
3,4704170965,KwamealaskaPb,1616462218932920320,2023-01-20T15:46:40.000Z,GQCGS 🔞🔞450+ ODDS \n🏀🏀🏀🏀🏀🏀🏀🏀🏀🏀\n\nFl...,0.0,0.0,NaN,NaN,NaN,NaN
4,1561041667569885187,anarchistdomme,1614617457813065731,2023-01-15T13:36:14.000Z,@saucynightgal you can try to email them to ge...,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
495,3271529856,HiCallViaMe,1611451144315834368,2023-01-06T19:54:26.000Z,@ImaginingsRpg @MerricB I'm sure WoTC will try...,0.0,0.0,NaN,NaN,NaN,NaN
496,1260826255,pccoc,1616460035701477378,2023-01-20T15:37:59.000Z,@MarshaBlackburn Where is the Republican Party...,0.0,0.0,NaN,NaN,NaN,NaN
497,1460093407989092354,zclhenle,1610846970209533954,2023-01-05T03:53:40.000Z,@chenlebase @TwitterSupport @g_gary53 Hello @T...,1.0,1.0,0.0,0.0,1.0,1.0
498,473353415,trlaOravis,1617272322377015296,2023-01-22T21:25:43.000Z,@RevolutApp I immediately contacted support to...,1.0,1.0,0.0,0.0,0.0,0.0
499,90480218,RichardGrenell,1617651018883530753,2023-01-23T22:30:32.000Z,"Whoa! @att and @directv deplatforming Newsmax,...",0.0,0.0,NaN,NaN,NaN,NaN

In [60]:
ra_train_frames1 = pd.read_csv('../dataverse_repo/data/research_assistants_data/problem_solution_task/training_data_problem_solution.csv')
ra_train_frames1 # completely different labelling (both/neither/solution/moderation)

,status_id,Date,text,relevant_paula,relevant_fabio,problem_frame_paula,problem_frame_fabio,solution_frame_paula,solution_frame_fabio,relevance_agreement_check,problem_solution_agreement_check,problem_solution_ra
0,1274037131636285443,2020-06-19T00:00:00Z,"The First Amendment binds the government, not ...",1,1,0,0.0,0,0,True,True,Neither
1,1236472965983657986,2020-03-08T00:00:00Z,"hi, my main acc @DEMINATIONIST is currently su...",1,1,0,0.0,0,0,True,True,Neither
2,1248195673771528194,2020-04-09T00:00:00Z,After a report showed a surge in misinformatio...,1,1,0,0.0,1,1,True,True,Solution
3,1313663759727067136,2020-10-07T00:00:00Z,Game 2 of the NLDS gets underway tomorrow at 2...,0,0,0,0.0,0,0,True,True,Neither
4,1224351561134022656,2020-02-03T00:00:00Z,"@connybush Sorry hun, Ive removed the tags on ...",0,0,0,0.0,0,0,True,True,Neither
...,...,...,...,...,...,...,...,...,...,...,...,...
2378,1233783871340208135,2020-02-29T00:00:00Z,@adopt_account I block when people unfollow...,0,0,0,0.0,0,0,True,True,Neither
2379,1259265991449739264,2020-05-09T00:00:00Z,#Facebook has banned the iconic photograph of ...,1,1,1,1.0,1,1,True,True,Both
2380,1319959818111692800,2020-10-24T00:00:00Z,"Trump said he wouldn’t cut Medicaid, Social Se...",0,0,0,0.0,0,0,True,True,Neither
2381,1299334898789036032,2020-08-28T00:00:00Z,Falken duffel bag weekly #giveaway #contest. R...,0,0,0,0.0,0,0,True,True,Neither
2382,1317881149558083585,2020-10-18T00:00:00Z,Eleribu ni e ooo!\r\nStop using my name to spr...,1,1,0,0.0,1,1,True,True,Solution

In [31]:
ra_final2

,status_id,Date,text,relevant_paula,relevant_fabio,problem_frame_paula,problem_frame_fabio,solution_frame_paula,solution_frame_fabio
0,1274037131636285443,2020-06-19,"The First Amendment binds the government, not ...",1.0,1.0,0.0,0.0,0.0,0.0
1,1312433590693756928,2020-10-03,Check out our fringe at #Lab2020 with @antisem...,1.0,0.0,0.0,0.0,0.0,0.0
2,1236472965983657986,2020-03-08,"hi, my main acc @DEMINATIONIST is currently su...",1.0,1.0,0.0,0.0,0.0,0.0
3,1248195673771528194,2020-04-09,After a report showed a surge in misinformatio...,1.0,1.0,0.0,0.0,1.0,1.0
4,1313663759727067136,2020-10-07,Game 2 of the NLDS gets underway tomorrow at 2...,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4995,1268582213970362368,2020-06-04,This man started an account where he tweets ex...,NaN,NaN,NaN,NaN,NaN,NaN
4996,1320592590979371010,2020-10-26,Pakistani PM Khan calls on Facebook to ban all...,NaN,NaN,NaN,NaN,NaN,NaN
4997,1312037128449138688,2020-10-02,@SupportRequests #0174895295 the google accoun...,NaN,NaN,NaN,NaN,NaN,NaN
4998,1256665133587279872,2020-05-02,@Yakekoge @NancyHazen16 @lisalbarjas1 @dieteri...,NaN,NaN,NaN,NaN,NaN,NaN
4999,1287068465908588550,2020-07-25,If anyone has managed to download and save any...,NaN,NaN,NaN,NaN,NaN,NaN